.PHONY: build clean check hooks changelog

build:
	@./build.sh

clean:
	@./build.sh clean

check: build
	@echo "✅ Build check passed"

hooks:
	@git config core.hooksPath .githooks
	@echo "✅ Git hooks activated (.githooks)"

changelog:
	@echo "📋 CHANGELOG.md is auto-generated by CI on each release to main."
	@echo "   To preview: cat CHANGELOG.md"
